### ISSUE TITLE
add a dependabot for monthly package updates

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/howto#41]
this repo could be reactive to package dependency updates. {renv} alone provides a static snapshot of the repo in the past, but this is not automatically reactive to dependency updates.

this feature is part of the carpentries workbench with a monthly PR created by a dependabot (?)

@Bisaloo would it be possible to implement a similar tooling or any more appropriate for the aim of this repo?

**Comment by Bisaloo** [comment]
In the short term, I would recommend you do manual updates as this is a complex task that I can't fit in my schedule right now.

One idea would be to reuse the Carpentries infrastructure but as far as I can tell, it quite strongly tailored for workbench repos at the moment and it's difficult to wrap my head around what would need to be adapted.

**Comment by avallecam** [comment]
I totally understand, thank you for your assessment!
