### ISSUE TITLE
should we make the code ready to copy and paste for reuse?

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/howto#43]
_originally suggested by @adamkucharski_ 

one approach would be to have: 
- runnable chunks 
- with no intermediate outputs to be printed and 
- with "the" table or figure at the end as proof of the capacity of the script to solve the problem

other one is encouraging to clone and reuse from repo. Actually, from the template we expect all "steps in code" to be within one chunk only.

**Comment by avallecam** [comment]
reference:
- https://www.reconverse.org/incidence2/articles/incidence2.html#computing-incidence-from-a-linelist
- https://github.com/reconverse/incidence2/blob/fa764c65452b4ebfc28245299900717367599254/vignettes/incidence2.Rmd#L10-L19
- or simpler, remove the code lines that call the printing

**Comment by avallecam** [comment]
alternatively, @adamkucharski proposes to use [tabset panels](https://quarto.org/docs/interactive/layout.html#tabset-panel) to show output code in one tab, and ready to copy and paste in a second tab.

**Comment by chartgerink** [comment]
Making it copy-pasteable is a great idea! For the latest quarto version, it only requires an update to the `_quarto.yml` file: https://github.com/quarto-dev/quarto-web/blob/1ef8c3c4ba444687a27513aa6a63076b934927df/_quarto.yml#L648

For documentation with code, I recommend taking a look at the Stripe docs. They are some of the best I've seen: https://docs.stripe.com/api

If you are interested in reproducible/executable code within the browser, it might be a great test case for [`webR`](https://jamesgoldie.dev/writing/your-new-r-package-webr/). If that is of interest we could do a trial run and report back what we learned.

**Comment by Bisaloo** [comment]
If I understand correctly, the current issue is that you need a way to concatenate all the code chunk into a single chunk, isn't it? Then, it's doable with a knitr hook and we can have it in a `<details>` section at the end of the page:

<details><summary>Full code</summary>

```r
# Here is the entire code to copy/paste

```

</details>

**Comment by avallecam** [comment]
thank you for both replies.

> Making it copy-pasteable is a great idea! For the latest quarto version, it only requires an update to the `_quarto.yml` file: https://github.com/quarto-dev/quarto-web/blob/1ef8c3c4ba444687a27513aa6a63076b934927df/_quarto.yml#L648

Nice feature. Hopefully the [copy button](https://quarto.org/docs/output-formats/html-code.html#copy-button) in quarto is enabled by default

> If I understand correctly, the current issue is that you need a way to concatenate all the code chunk into a single chunk, isn't it? Then, it's doable with a knitr hook and we can have it in a `<details>` section at the end of the page:

this looks doable. so, If we name a chuck, like [this whole chunk](https://github.com/epiverse-trace/howto/blob/main/analyses/quantify_transmission/reproduction_number_effective_finalsize.qmd#L21-L90), we could make it visible at the end?  

# the issue

To rephrase the issue, intermediate outputs are shown out of the chunk, cutting the content that the copy button covers. While on package websites output is printed within the chunk (looking like a reprex output)

My question is, what style or knit options feature could we replicate from {pkgdown} to replicate this behaviour in a quarto website? I though this could be more easy to implement, but the easiest you suggest is welcome!

# what we want
![image](https://github.com/epiverse-trace/howto/assets/21230390/0552cc19-11e8-4c42-901e-f236aafde01e)

# what we have
![image](https://github.com/epiverse-trace/howto/assets/21230390/49eba125-c01c-4374-a1dc-0cd7587ce3ef)

an expected result of the improvement would be

```r
demography_vector
#> [1]  3453670  9761554 18110368 19288101  9673058

demography_groups
#> [1] "[0,5)"   "[5,18)"  "[18,40)" "[40,65)" "65+"    
```

**Comment by Bisaloo** [comment]
If you want to replicate the pkgdown behaviour, this is the relevant line:

https://github.com/epiverse-trace/ColOpenData/blob/ab7ac6f27c5ef811c59fddbc2dd40c552b10684b/vignettes/demographic_data.Rmd#L15

**Comment by Bisaloo** [comment]
You're right! Looks like `collapse = TRUE` is necessary as well for the desired effect: https://github.com/epiverse-trace/ColOpenData/blob/ab7ac6f27c5ef811c59fddbc2dd40c552b10684b/vignettes/demographic_data.Rmd#L13-L16

**Comment by avallecam** [comment]
> You're right! Looks like `collapse = TRUE` is necessary as well for the desired effect: https://github.com/epiverse-trace/ColOpenData/blob/ab7ac6f27c5ef811c59fddbc2dd40c552b10684b/vignettes/demographic_data.Rmd#L13-L16

ok, done, I thought that collapse action was to fold the code chunk, haha, thanks!
![image](https://github.com/epiverse-trace/howto/assets/21230390/941af8f6-bd2f-4b4d-b458-e74311bf7873)
